name: Tests

on:
  push:
    branches:
      - "main"
      - "*-testme"
  pull_request:
    branches:
      - "main"

env:
  PANORAMA_HOSTNAME: test
  PANORAMA_KEY: test

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
          python -m pip install -e .

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0

      - name: Run tests
        run: |
          pytest
